ARG VERSION_EFK=6.2.4
ARG FLAVOUR_EFK="-oss"
FROM docker.elastic.co/kibana/kibana${FLAVOUR_EFK}:${VERSION_EFK}

LABEL Author="Lee Myring <mail@thinkstack.io>"
LABEL Description="Kibana instance"
LABEL Version="1.0.0"
