ARG VERSION_ELK
ARG FLAVOUR_ELK
FROM docker.elastic.co/kibana/kibana${FLAVOUR_ELK}:${VERSION_ELK}

LABEL Author="Lee Myring <mail@thinkstack.io>"
LABEL Description="Kibana instance"
LABEL Version="0.1"
